### ISSUE TITLE
Question related to train and inference

### ISSUE THREAD

**Issue by AnushaManila** [syinari0123/tridepth#3]
Hi,

I'm interested in your work MeshDepth and I have successfully prepared the environment. 
'Train.py' breaks at line 41, in resolve_self_intersection. 

Also, (by using the pre-trained model) inference.py gives output (4, 2) (4, 2) and nothing is seen inside result folder.

Any hints are appreciated.

Thanks & Regards

**Comment by meshdepth** [comment]
Thank you for having an interest in our work.
Your problem seems to be caused by the wrong version of Pymesh. (related to this issue https://github.com/syinari0123/tridepth/issues/2)
You need to install it from source code, not from pip package.
(Pip version does not support 'snap_rounding.')

Please try this! If you have any trouble, please report again here!

**Comment by syinari0123** [comment]
Thank you for having an interest in our work.
Your problem seems to be caused by the wrong version of Pymesh. (related to this issue #2)
You need to install it from source code, not from pip package.
(Pip version does not support 'snap_rounding.')

Please try this! If you have any trouble, please report again here!

**Comment by AnushaManila** [comment]
Thank you for your reply. I will reinstall pymesh from the source. Seems like I have two pymesh installations(both 0.2.1) and it needs to be fixed. I'll get back to you asap

**Comment by syinari0123** [comment]
I suspect your triangle package may not be installed correctly...
Could you check that your triangle package really works well in your environment (see https://rufat.be/triangle/examples.html)?

For your information, the version of triangle package in my environment is "20190115.3". Please check it!

**Comment by AnushaManila** [comment]
Thanks for your suggestion. I had the same version of triangle as yours but the examples didn't work. 
I had to manually copy the .so files to the site-package and that worked!

But now the train and inference scripts throw error below:
module 'tridepth_renderer.renderer.cuda' has no attribute 'forward_face_index_map'

I'll take a look into it and see what could have caused it.

Thank you!

**Comment by syinari0123** [comment]
I think your folder structure is correct.
After you run the following cuda-renderer installation command, tridepth_renderer package would be installed in your pip environment. (you can see 'tridepth-renderer 0.0.0' if you run ```pip list```)
```
cd tridepth/renderer/cuda/
python setup.py install
```
Could you check it?
There may be something wrong in your pip environment...:(

**Comment by AnushaManila** [comment]
Thanks a lot!

I was using the miniconda environment. So the' tridepth_renderer' got installed inside the miniconda environment site-packages. So I copied the generated directory to the working directory which fixed the 'tridepth_renderer' module importing issue.

Now the inference and train scripts work well in my environment set-up. 
Thank you for your suggestions and the issues are solved. Hence closing it now.
